version: '3'

services:
  mypostgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mike
    ports:
      - 5432:5432
    
    networks:
      - mynetwork
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true